/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "alibaba_create-order": () => import("@/views/alibaba/create-order/index.vue"),
  "alibaba_order-detail": () => import("@/views/alibaba/order-detail/index.vue"),
  "alibaba_order-list": () => import("@/views/alibaba/order-list/index.vue"),
  "alibaba_search-product": () => import("@/views/alibaba/search-product/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "ozon_auto-listing": () => import("@/views/ozon/auto-listing/index.vue"),
  "ozon_calibration-queue": () => import("@/views/ozon/calibration-queue/index.vue"),
  "ozon_commission-rate": () => import("@/views/ozon/commission-rate/index.vue"),
  "ozon_listing-record": () => import("@/views/ozon/listing-record/index.vue"),
  ozon_mapping: () => import("@/views/ozon/mapping/index.vue"),
  ozon_pricing: () => import("@/views/ozon/pricing/index.vue"),
  ozon_product: () => import("@/views/ozon/product/index.vue"),
  ozon_search: () => import("@/views/ozon/search/index.vue"),
  ozon_weight: () => import("@/views/ozon/weight/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_seller: () => import("@/views/system/seller/index.vue"),
};
