/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';
import { onRenderTracked } from 'vue';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'alibaba',
    path: '/alibaba',
    component: 'layout.base',
    meta: {
      title: 'alibaba',
      i18nKey: 'route.alibaba',
      icon: 'ant-design:alibaba-outlined',
      order: 1
    },
    children: [
      {
        name: 'alibaba_create-order',
        path: '/alibaba/create-order',
        component: 'view.alibaba_create-order',
        meta: {
          title: 'alibaba_create-order',
          i18nKey: 'route.alibaba_create-order',
          hideInMenu: true,
          hideFooter: true
        }
      },
      {
        name: 'alibaba_order-detail',
        path: '/alibaba/order-detail',
        component: 'view.alibaba_order-detail',
        meta: {
          title: 'alibaba_order-detail',
          i18nKey: 'route.alibaba_order-detail',
          icon: 'tdesign:order',
          hideInMenu: true
        }
      },
      {
        name: 'alibaba_order-list',
        path: '/alibaba/order-list',
        component: 'view.alibaba_order-list',
        meta: {
          title: 'alibaba_order-list',
          i18nKey: 'route.alibaba_order-list',
          icon: 'ant-design:alipay-outlined',
          order: 2
        }
      },
      {
        name: 'alibaba_search-product',
        path: '/alibaba/search-product',
        component: 'view.alibaba_search-product',
        meta: {
          title: 'alibaba_search-product',
          i18nKey: 'route.alibaba_search-product',
          icon: 'bi:search',
          order: 1
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 0
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ozon',
    path: '/ozon',
    component: 'layout.base',
    meta: {
      title: 'ozon',
      i18nKey: 'route.ozon',
      icon: 'cib:apache-spark',
      order: 2
    },
    children: [
      {
        name: 'ozon_auto-listing',
        path: '/ozon/auto-listing',
        component: 'view.ozon_auto-listing',
        meta: {
          title: 'ozon_auto-listing',
          i18nKey: 'route.ozon_auto-listing',
          icon: 'streamline-color:auto-flash-flat',
          order: 1
        }
      },
      {
        name: 'ozon_calibration-queue',
        path: '/ozon/calibration-queue',
        component: 'view.ozon_calibration-queue',
        meta: {
          title: 'ozon_calibration-queue',
          i18nKey: 'route.ozon_calibration-queue',
          icon: 'streamline-kameleon-color:scale-weight-duo',
          order: 7
        }
      },
      {
        name: 'ozon_commission-rate',
        path: '/ozon/commission-rate',
        component: 'view.ozon_commission-rate',
        meta: {
          title: 'ozon_commission-rate',
          i18nKey: 'route.ozon_commission-rate',
          icon: 'streamline-freehand-color:business-coaching-strategy-1',
          order: 8
        }
      },
      {
        name: 'ozon_listing-record',
        path: '/ozon/listing-record',
        component: 'view.ozon_listing-record',
        meta: {
          title: 'ozon_listing-record',
          i18nKey: 'route.ozon_listing-record',
          order: 5,
          icon: 'material-symbols:azm-outline'
        }
      },
      {
        name: 'ozon_mapping',
        path: '/ozon/mapping',
        component: 'view.ozon_mapping',
        meta: {
          title: 'ozon_mapping',
          i18nKey: 'route.ozon_mapping',
          icon: 'material-symbols:all-match-outline',
          order: 4
        }
      },
      {
        name: 'ozon_pricing',
        path: '/ozon/pricing',
        component: 'view.ozon_pricing',
        meta: {
          title: 'ozon_pricing',
          i18nKey: 'route.ozon_pricing',
          icon: 'hugeicons:sale-tag-02',
          order: 6
        }
      },
      {
        name: 'ozon_product',
        path: '/ozon/product',
        component: 'view.ozon_product',
        meta: {
          title: 'ozon_product',
          i18nKey: 'route.ozon_product',
          icon: 'streamline:mail-send-email-send-email-paper-airplane',
          order: 2
        }
      },
      {
        name: 'ozon_search',
        path: '/ozon/search',
        component: 'view.ozon_search',
        meta: {
          title: 'ozon_search',
          i18nKey: 'route.ozon_search',
          icon: 'streamline:interface-content-fire-lit-flame-torch-trending',
          order: 3
        }
      },
      {
        name: 'ozon_weight',
        path: '/ozon/weight',
        component: 'view.ozon_weight',
        meta: {
          title: 'ozon_weight',
          i18nKey: 'route.ozon_weight',
          icon: 'streamline-kameleon-color:scale-weight-duo',
          order: 100,
          hideInMenu: true
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'hugeicons:system-update-01',
      order: 100
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config',
          icon: 'material-symbols:settings-cinematic-blur-outline',
          order: 1
        }
      },
      {
        name: 'system_seller',
        path: '/system/seller',
        component: 'view.system_seller',
        meta: {
          title: 'system_seller',
          i18nKey: 'route.system_seller',
          icon: 'material-symbols:settings-account-box-outline',
          order: 2
        }
      }
    ]
  }
];
