/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';
import { onRenderTracked } from 'vue';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ozon',
    path: '/ozon',
    component: 'layout.base',
    meta: {
      title: 'ozon',
      i18nKey: 'route.ozon',
      icon: 'streamline-ultimate:e-commerce-touch-buy-bold',
      order: 2
    },
    children: [
      {
        name: 'ozon_mapping',
        path: '/ozon/mapping',
        component: 'view.ozon_mapping',
        meta: {
          title: 'ozon_mapping',
          i18nKey: 'route.ozon_mapping',
          icon: 'material-symbols:all-match-outline',
          order: 3
        }
      },
      {
        name: 'ozon_product',
        path: '/ozon/product',
        component: 'view.ozon_product',
        meta: {
          title: 'ozon_product',
          i18nKey: 'route.ozon_product',
          icon: 'streamline:interface-calendar-check-approve-calendar-check-date-day-month-success',
          order: 1
        }
      },
      {
        name: 'ozon_search',
        path: '/ozon/search',
        component: 'view.ozon_search',
        meta: {
          title: 'ozon_search',
          i18nKey: 'route.ozon_search',
          icon: 'streamline:interface-content-fire-lit-flame-torch-trending',
          order: 2
        }
      }
    ]
  },
  {
    name: 'product',
    path: '/product',
    component: 'layout.base$view.product',
    meta: {
      title: 'product',
      i18nKey: 'route.product',
      icon: 'streamline:interface-calendar-check-approve-calendar-check-date-day-month-success',
      order: 3
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'hugeicons:system-update-01',
      order: 100
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config',
          icon: 'material-symbols:settings-cinematic-blur-outline',
          order: 1
        }
      }
    ]
  }
];
